# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: synoriq
service: hrms-login-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: 
        - "arn:aws:dynamodb:us-east-1:905418102294:table/users"

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: 
            origin: '*'  # Replace '*' with your allowed origin for production
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false  # Set to true if you want to support credentials

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
